name: Build macOS Application

on:
  push:
    tags:
      - 'v*'  # 仅在以 'v' 开头的标签时触发
env:
  APP_NAME: "V2rayPanel"
  APP_DIR: "V2rayPanel.app"


jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        architecture: [arm64]  # amd64 for Intel, arm64 for M2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'  # 设置 Go 版本

      - name: Build the application
        run: |
          GOOS=darwin GOARCH=${{ matrix.architecture }} go build -o bin/v2ray_${{ matrix.architecture }} cmd/client/main.go

      - name: Create macOS app bundle
        run: |
          VERSION="1.0.0"
          
          mkdir -p "${{ env.APP_DIR }}/Contents/MacOS"
          cp "bin/v2ray_${{ matrix.architecture }}" "${{ env.APP_DIR }}/Contents/MacOS/${{ env.APP_NAME }}"
          
          # 创建 Info.plist
          cat > "${{ env.APP_DIR }}/Contents/Info.plist" <<EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleName</key>
              <string>${{ env.APP_NAME }}</string>
              <key>CFBundleVersion</key>
              <string>${VERSION}</string>
              <key>CFBundleIdentifier</key>
              <string>com.example.${{ env.APP_NAME }}</string>
              <key>CFBundleExecutable</key>
              <string>${{ env.APP_NAME }}</string>
          </dict>
          </plist>
          EOL

      - name: Archive the application
        run: |
          zip -r "${{ env.APP_NAME }}_${{ matrix.architecture }}.zip" "${{ env.APP_DIR }}"

#      - name: Upload the application
#        uses: actions/upload-artifact@v4
#        with:
#          name: "${{ env.APP_NAME }}_${{ matrix.architecture }}.zip"
#          path: "${{ env.APP_NAME }}_${{ matrix.architecture }}.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # 使用当前标签作为 tag_name
          release_name: Release ${{ github.ref }}  # 使用当前标签作为 release_name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.APP_NAME }}_${{ matrix.architecture }}.zip