name: Build macOS Application

on:
  push:
    tags:
      - 'v*'  # 仅在以 'v' 开头的标签时触发
env:
  APP_NAME: "v2ray"

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [arm64]  # amd64 for Intel, arm64 for M2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2'  # 设置 Go 版本

      - name: Build the application
        run: |
          GOOS=darwin GOARCH=${{ matrix.arch }} go build -o bin/${{ env.APP_NAME }}${{ matrix.arch }} cmd/client/main.go
          chmod +x bin/v2ray_${{ matrix.arch }}

      - name: Archive the application
        run: |
          zip -r "${{ env.APP_NAME }}_${{ matrix.arch }}.zip" "${{ env.APP_DIR }}"

#      - name: Upload the application
#        uses: actions/upload-artifact@v4
#        with:
#          name: "${{ env.APP_NAME }}_${{ matrix.architecture }}.zip"
#          path: "${{ env.APP_NAME }}_${{ matrix.architecture }}.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}  # 使用当前标签作为 tag_name
          release_name: Release ${{ github.ref }}  # 使用当前标签作为 release_name
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.APP_NAME }}_${{ matrix.arch }}.zip